[package]
name = "binding"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
envmnt = "0.10.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
glob = "0.3"
cc = "1.0.83"
bindgen = "0.69.2"
